pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "approved-reviews-by>=1"
      - "check-success=Semantic Pull Request"
      - "check-success=terraform-kubernetes-addons / linter (pull_request)"
      - "check-success=terraform-kubernetes-addons / terraform:generic (pull_request)"
      - "check-success=terraform-kubernetes-addons / terraform:aws (pull_request)"
      - "check-success=terraform-kubernetes-addons / terraform:scaleway (pull_request)"
    actions:
      merge:
        method: merge
